modLoader = "javafml"
loaderVersion = "[31,)"
issueTrackerURL = "${mod_issues_url}"
license = "MIT"

[[mods]]
modId = "tis3d"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "${mod_url}"
#logoFile = "logo.png"
authors = "Sangar"
description = '''
TIS-100 inspired low-tech computing for Minecraft.
'''

[[mods]]
modId = "markdown_manual"
version = "1.0.0"
displayName = "Markdown Manual"
authors = "Sangar"
description = '''
Library mod providing a convenient way of defining in-game manuals.
'''

[[dependencies.tis3d]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version_min},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.tis3d]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version_min}]"
ordering = "NONE"
side = "BOTH"
[[dependencies.tis3d]]
modId = "markdown_manual"
mandatory = true
versionRange = "[1.0.0,)"
side = "CLIENT"
