modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/MightyPirates/TIS-3D/issues"
license = "MIT"

[[mods]]
modId = "tis3d"
version = "${file.jarVersion}"
displayName = "TIS-3D"
displayURL = "https://github.com/MightyPirates/TIS-3D"
#logoFile = "logo.png"
authors = "Sangar"
description = '''
TIS-100 inspired low-tech computing for Minecraft.
'''

[[dependencies.tis3d]]
modId = "forge"
mandatory = true
versionRange = "41.0.105,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.tis3d]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.19.1)"
ordering = "NONE"
side = "BOTH"
[[dependencies.tis3d]]
modId = "markdown_manual"
mandatory = true
versionRange = "[1.2.2,)"
side = "CLIENT"
